### ISSUE TITLE
アカウントの削除 画面作成

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#112]
アカウントの削除 画面作成

<img width="304" alt="スクリーンショット 2023-10-03 1 04 52" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/1180fb90-79fd-4d25-85cb-0312a81b3dc6">

_Originally posted by @ken-ty in https://github.com/Mayumi-Nakabayashi/withTone/issues/59#issuecomment-1743298149_

**Comment by sodateya** [comment]
https://github.com/Mayumi-Nakabayashi/withTone/pull/122
作成しました
