### ISSUE TITLE
learning_community_search画面 キーボードが持ち上がった際のレンダリングエラー

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#19]
learning_community_search画面 キーボードが持ち上がった際のレンダリングエラー

キャプチャに示した OverFlow を対応する

キャプチャ:
<img alt="learning community search" width="200" src="https://user-images.githubusercontent.com/64653733/262074133-7be3b74e-b557-4d14-8ea5-fc4cfc21a0cf.png">

_Originally posted by @ken-ty in https://github.com/Mayumi-Nakabayashi/withTone/issues/17#issuecomment-1687428853_

**Comment by ken-ty** [comment]
#41 の問題も

**Comment by sodateya** [comment]
## 解消？
https://github.com/Mayumi-Nakabayashi/withTone/pull/119
