### ISSUE TITLE
動画関連機能の資料集め（パッケージの検討）

### ISSUE THREAD

**Issue by yuuya-1205** [Mayumi-Nakabayashi/withTone#32]
## 説明

動画関連のタスクを整理する為に、パッケージの検討や資料を集めます。

## ゴール

- 動画関連のタスクを整理し、全て Issue にする
  - 実装参考になりそうな 資料やオススメパッケージは記載しておく

**Comment by ken-ty** [comment]
ffmpeg
https://pub.dev/packages/ffmpeg_kit_flutter

**Comment by ken-ty** [comment]
video playder

**Comment by yuuya-1205** [comment]
とりあえず、動画は表示のみさせる。

https://github.com/salvadordeveloper/TikTok-Flutter/blob/master/lib/data/videos_firebase.dart

これを参考に作る。

**Comment by ken-ty** [comment]
https://github.com/Mayumi-Nakabayashi/withTone/issues/74#issuecomment-1744472243

にて、この issue を関連 issue に追記した。
ここでの調査対応は Done 。 より詳細は各 issue で実装時に行う。
