### ISSUE TITLE
共同開発として Flutter 大学内でメンバーを募集する

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#35]
## 説明

withTone プロジェクトは 共同開発として実施いたします。
共同開発します！の宣言時に、追加メンバーを募集します。

## ゴール

- 追加メンバーどんな人にするか？決める。
- 共同開発発表で使う資料を作成する（いらないかも？共同開発の流れがわからないです）
- 共同開発のスタート発表する。メンバーを募集する。
- 追加メンバーのキャッチアップをして、Issue を振るところまで行う。
- メンバー追加後のMTGで問題なければ Close する。

**Comment by yuuya-1205** [comment]
これ、ちと話し合いたいです！

【懸念要素が２点】
・全体バランスが崩れる気がしてならない。
→入れてもあと２人かなと。（石川さんの負担を減らす目的で）
→僕が個人面談して入れる人を絞りたい。

・人数が増えたことによるレビュワーの負担増大。
→現在のレビュワー　ken-tyさんとyuiさんに任せていて負担が増えるのではないかと思っているため。

**Comment by ken-ty** [comment]
@yuuya-1205 

以前Meetで会話しましたが、現状自分は以下の考えですー！

> 【懸念要素が２点】
> ・全体バランスが崩れる気がしてならない。
> →入れてもあと２人かなと。（石川さんの負担を減らす目的で）
> →僕が個人面談して入れる人を絞りたい。

共同発表会として Flutter 大学内で開発者を募ります。
現状良きメンバーが揃っているので、参加募集には一定の条件を設けます。

うしさんに面談していただき、自走出来る方や、現在のメンバーが一緒に開発したいメンバーを優先して採用して頂きます。

↑ 一緒に開発したい... は現状メンバーの直接指名なら信頼に足る、と考える為です！

> ・人数が増えたことによるレビュワーの負担増大。
> →現在のレビュワー　ken-tyさんとyuiさんに任せていて負担が増えるのではないかと思っているため。

気にかけて頂き感謝です 🙏  MTG で会話した通り、 もっとラフにマージしていきましょう、という流れで。

**Comment by ken-ty** [comment]
α版リリース後のヒアリングにご協力いただける方、β版を使ってくれる方を募集してもよさそう。

**Comment by ken-ty** [comment]
@Mayumi-Nakabayashi 
#53 に共同開発成果発表会に向けた資料作成まとめているので、参考にしながら 共同開発開始の発表会の流れを組んでいただければ！

**Comment by Mayumi-Nakabayashi** [comment]
@ken-ty 
最高ーー！！ありがとうございます！勉強します！

**Comment by ken-ty** [comment]
リーダーズ発表お疲れ様でした！こちら close します！
