### ISSUE TITLE
マイルストーン作成

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#37]
## 説明

ざっくり日程を中日程として解像度を挙げてマイルストーンにする。
マイルストーンに Issue を立てて、やるべきことを洗い出す。
洗い出した内容を タスクにブレイクダウンしていき、担当者を決めて割り当てできるようにする。

上記の マイルストーン作成 までが今回やるべきこと

## ゴール

- [x] 中日程のマイルストーンを作成する
- [ ] 中日程について、メンバー全員の合意を取る。認識を合わせる。

---

うしさんの書いてくれた中日程をコピー
```
2023年8月31日 　仕様決め・仕様書作成

議事録：

 

2023年9月7日 　仕様決め・仕様書作成

議事録：

 

2023年9月14日 　仕様決め・仕様書作成

議事録：

 

2023年9月21日 　タスク作成

議事録：

 

2023年9月28日 　タスク作成

議事録：

 

2023年10月5日 　リーダーズで発表

議事録：

 

2023年10月12日 　メンバー決定　＋　タスク割り振り

議事録：

 

2023年10月19日 　スプリント1週目

議事録：

 

2023年10月26日 　スプリント2週目

議事録：

 

2023年11月2日 　   スプリント3週目

議事録：

 

2023年11月9日 　   スプリント4週目

議事録：

 

2023年11月16日 　  スプリント5週目

議事録：

 

2023年11月23日 　  スプリント6週目

議事録：

 

2023年11月30日 　  スプリント7週目

議事録：

 

2023年12月7日 　　スプリント8週目

議事録：

 

2023年12月14日 　  発表資料作成　（予備）

議事録：

 

　【記入例】

　　・目次

　　・学んだこと

　　・メンバーの学んだこと

 

この辺にリンク貼る　共有したいから。

 

2023年12月21日 　発表資料作成完了（予備）

議事録：

 

　【メンバー資料確認】

　　・うし　

　　・まゆみ　

　　・ken-ty　

　　・yui　　

 

2023年12月26日 

発表会　リリース


```

**Comment by ken-ty** [comment]
日程(締切), やるべきこと:

- 2023年9月14日 　仕様決め・仕様書作成
- 2023年9月28日 　タスク作成
- 2023年10月5日 　リーダーズで発表
  - リーダーズとは？？ 
- 2023年10月12日 　メンバー決定　＋　タスク割り振り
- 2023年12月7日 　　スプリント1 ~ 8週 で開発
- 2023年12月14日 　  発表資料作成　（予備）
- 2023年12月21日 　発表資料作成完了（予備）
- 2023年12月26日  発表会　リリース

**Comment by ken-ty** [comment]
現状の方針だと、一旦 レイアウトだけ作っちゃおうぜ！でやっている。
動かせるものがあるなら、12/26 の本リリース前に α版、β版として限られたユーザーに触れてもらったフィードバックを反映できるか？

**Comment by ken-ty** [comment]
- 最低限版のUI固める →最低限の機能を持たせて開発 → α版リリース（クローズドテスト）、ここまでの開発をスライドにまとめる
- α版 のフィードバックから、実際にリリースする想定の機能を洗い出し実装する。 → β版リリース（クローズドテスト）、ここまでの開発をスライドにまとめる
- β版で 不具合修正、機能やレイアウトの微調整（本リリース前にばっこり変更はしない、スコープクリープする）→ 本リリース、ここまでの開発をスライドにまとめる

- めっちゃ実装時間かかるしなくても動くようなものは、後回しにして本リリース後に対応する

**Comment by ken-ty** [comment]
仕様書作成 → 本リリース前提で作って良い。ただし、どれをアルファ版でやるかどうか仕分けする。

**Comment by yuuya-1205** [comment]
10月末までにα版を完成させる。
11月2週はヒヤリング
11月3-4週はまゆみさんの要望を聞きながら実装
12月はなんかやる。

**Comment by ken-ty** [comment]
11/11 北海道旅行！！！！！！！！！

**Comment by ken-ty** [comment]
上記までを反映して更新:

| 日程(締切) | やるべきこと | 備考 |
| --- | --- | --- |
| 2023年9月14日 |  仕様決め・仕様書作成 | --- |
| 2023年9月28日 |  タスク作成 | --- |
| 2023年10月5日 |  リーダーズの発表 | メンバー増える  |
| 2023年10月12日 |  スプリント1 ~ 8週 で開発 | --- |
| 2023年11月01日 |  α版リリース | 開発と並行してヒアリング進める |
| 2023年11月11日 |  α版リリースお疲れ様オフ会 in 北海道 | 全員分のポッキー/プリッツを用意 |
| 2023年12月01日 |  β版リリース | 不具合なければこのまま12/26リリースへ |
| 2023年12月7日 |  発表資料作成完了（予備） | --- |
| 2023年12月14日 |  発表資料作成完了（予備） | --- |
| 2023年12月26日 |  発表会　リリース | --- |

**Comment by ken-ty** [comment]
マイルストーンに反映します

**Comment by ken-ty** [comment]
マイルストーンに反映 Done

**Comment by ken-ty** [comment]
各マイルストーンに Issue を振っていくのは、 https://github.com/Mayumi-Nakabayashi/withTone/milestone/6 で行います。

**Comment by ken-ty** [comment]
@Mayumi-Nakabayashi @yuuya-1205 

> 上記までを反映して更新:
> 
> 日程(締切)	やるべきこと	備考
> 2023年9月14日	仕様決め・仕様書作成	---
> 2023年9月28日	タスク作成	---
> 2023年10月5日	リーダーズの発表	メンバー増える
> 2023年10月12日	スプリント1 ~ 8週 で開発	---
> 2023年11月01日	α版リリース	開発と並行してヒアリング進める
> 2023年11月11日	α版リリースお疲れ様オフ会 in 北海道	全員分のポッキー/プリッツを用意
> 2023年12月01日	β版リリース	不具合なければこのまま12/26リリースへ
> 2023年12月7日	発表資料作成完了（予備）	---
> 2023年12月14日	発表資料作成完了（予備）	---
> 2023年12月26日	発表会　リリース	---

上記を元に マイルストーンを作成しました！
以下ご確認して認識合わせたい&指摘ありましたら教えて欲しいです！
https://github.com/Mayumi-Nakabayashi/withTone/milestones

この後としては、
 https://github.com/Mayumi-Nakabayashi/withTone/milestone/6
でタスクを挙げていけば良いと思ってます！

**Comment by ken-ty** [comment]
α版

- プロファイル（1w）
- ビデオ関連
  - 再生（2w）
  - 投稿どれくらいできる？？（見積もり α版・β版でどれくらい？）（3w）
  - ビデオ関連画面（4w）
- ソーシャルログイン関連 → 作らなくて良さげ（一旦メールのみ）(0)
- 資料作成（共同発表募集）（1w）
- UI ブラッシュアップ
- 各画面の状態とか
- 分析(0)
- 諸々2Ph

---

紙芝居 + 画面ごとの見積もり

**Comment by ken-ty** [comment]
リリースしたい内容
=> 2ph
=> β版
=> α版
スプリントどうするの
1

**Comment by ken-ty** [comment]
MTG で全体合意。
共同開発まわりわかりにくいので、 マイルストーンや issue のタイトルだけ調整するか。

**Comment by ken-ty** [comment]
共同開発周り調整ずみ。
マイルストーン作成 Done 。
Close します
