### ISSUE TITLE
admob どうするか決める

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#39]
6種類って何あるの？資料とかある？
→ @sodateya 

6種類の中から決めましょう
→ @Mayumi-Nakabayashi 

動くコードあるなら、参考にしたい。
→ @yuuya-1205 

話し合って、 admob どうするか決めていただけると！

**Comment by Mayumi-Nakabayashi** [comment]
@ken-ty 承知しました！

**Comment by sodateya** [comment]
ざっくりとしか書かれていませんが６種類の内容です！
https://renroku6.hatenablog.com/entry/2021/04/03/162829

実装時に参考にした資料(バナー、インターステイシャルの実装)
https://zenn.dev/mamushi/articles/flutter_ads_in_listview
https://yaba-blog.com/flutter-admob/
https://note.com/zigen_z4/n/nbcd2adf29520
https://zenn.dev/tama8021/articles/0808_flutter_admob_interstitial

**Comment by sodateya** [comment]
https://liskul.com/display-ads-banner-size-92523
バナーサイズ

**Comment by Mayumi-Nakabayashi** [comment]
@sodateya 

質問です！
定例でおっしゃってたIDって、↓のアプリIDと広告ユニットIDのことで大丈夫です？
認識間違ってたらご指摘ください！🙇‍♀️
https://support.google.com/admob/answer/7356431?hl=ja

**Comment by sodateya** [comment]
> @sodateya 
> 
> 
> 
> 質問です！
> 
> 定例でおっしゃってたIDって、↓のアプリIDと広告ユニットIDのことで大丈夫です？
> 
> 認識間違ってたらご指摘ください！🙇‍♀️
> 
> https://support.google.com/admob/answer/7356431?hl=ja


はい！アプリIDとユニットIDで大丈夫です！

**Comment by Mayumi-Nakabayashi** [comment]
<img width="967" alt="adtest" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/59502423/d4c78ae6-adfa-4110-aaf4-1d865e623f56">

@yuuya-1205 
広告デザインですが、↑の通り、仮で2案作成しました！サイズは石川さんにもらった記事を参考にしてます。

そして1点質問です！
バナーという流れでしたが、admobのバナーの動き（？）について、どこかのタイミングで擦り合わせることって可能でしょうか？
広告を調べてたら、SNSの主流な広告はインターステーシャルかなと思いますが、
どういう動きかによって、どのページに広告を表示させるか等、デザインも少し変わるかなと思いまして。。🧐

**Comment by Mayumi-Nakabayashi** [comment]
@sodateya 
IDの連絡遅れててすみません！
I D取得にはアプリを登録する必要があるのかな？と思ったので、ちょっとラーニングの時間ください〜！🙇‍♀️
調べて、やってみます！🙇‍♀️

**Comment by yuuya-1205** [comment]
@Mayumi-Nakabayashi 
デザインありがとうございます！

> バナーという流れでしたが、admobのバナーの動き（？）について、どこかのタイミングで擦り合わせることって可能でしょうか？

→定例のMTGの議題で話し合いますか！

> SNSの主流な広告はインターステーシャルかなと思ったんですが、
どういう動きかによって、どのページに広告を表示させるか等、デザインも少し変わるかなと思いまして。。🧐

→確かに変わりますね！
この辺りの流れとしては...
①バナー広告をとりあえず置く
②動画機能を実装してアプリの動きを確かめる。
③インターステーシャル広告を試してみる。

こんな流れを考えてます！

**Comment by Mayumi-Nakabayashi** [comment]
@yuuya-1205 
ありがとうございます、全て承知いたしました！

**Comment by Mayumi-Nakabayashi** [comment]
@sodateya 
Admob経由で、アプリIDと広告ユニットID（テストでバナー）をメールしました！

念の為アプリIDここにも書いておきますね。
iOS：ca-app-pub-6759177008690654~8996532581
Android:ca-app-pub-6759177008690654~7328227695

**Comment by ken-ty** [comment]
一旦実装済みなので、 Close しますね！
