### ISSUE TITLE
【Auth】ユーザーアイコンの表示

### ISSUE THREAD

**Issue by y129may9th** [Mayumi-Nakabayashi/withTone#47]
## 内容
ログインユーザーのアイコン表示

## ページ

content | professional | learning community home
-- | -- | --
<img width="375" alt="content" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/44105111/4daa1458-634b-46c1-bf2d-5b48c8306907"> | <img width="375" alt="professional" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/44105111/90855301-cfe9-48fc-89a7-932aea522d21"> | ![learning community home](https://github.com/Mayumi-Nakabayashi/withTone/assets/44105111/b12f0def-9931-415e-b771-a9d648283b67)

**Comment by ken-ty** [comment]
自分、他の人のユーザーアイコンを画面に表示する。

**Comment by ken-ty** [comment]
#158 終わり次第対応。
