### ISSUE TITLE
発表会に出る

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#54]
## 説明

勝ちます

## ゴール

発表すること

**Comment by ken-ty** [comment]
誰が発表する？とか、β版で発表する？とか、発表会前に決めておくべきことはここで話し合いましょう。

**Comment by yuuya-1205** [comment]
@Mayumi-Nakabayashi 
まゆみさんのプロダクトだからまゆみさんがやった方が良い気がしてきた！
僕がまゆみさんのピッチ見たいってのもあるんだけどね笑

**Comment by Mayumi-Nakabayashi** [comment]
@yuuya-1205 
私は、うしさんがやったほうがいいかなって思ってました😊
どこかで話し合いますか？


flutter大学の発表だったら、エンジニア向けの内容がいいのかな？って思うのと、リーダーとしてまとめてもらっているので！！
私だとbizdev周辺のピッチになっちゃうかも
もちろんプロダクトに愛があるので、資料は一緒に考えたいです！！！💪

**Comment by yuuya-1205** [comment]
@Mayumi-Nakabayashi 
話し合いますかね！

そしたら僕は『２人でやるを選択します』

僕が最初の掴みをやるのでまゆみさんにはbizdevのピッチやっていただければいいのかと！
プロダクト愛がある人が話した方がみんなに熱意が伝わります！

**Comment by Mayumi-Nakabayashi** [comment]
@yuuya-1205 
はーい！資料のドラフト考えておきますね！

**Comment by ken-ty** [comment]
予定引いた感じ、発表はベータ版開発中になりそうですね！

**Comment by ken-ty** [comment]
12/27 に発表らしい
