### ISSUE TITLE
パスワード再設定メールを送れるようにする

### ISSUE THREAD

**Issue by ken-ty** [Mayumi-Nakabayashi/withTone#73]
パスワード再設定メールを送れるようにする

Forgot password 画面、 Forgot password 2 画面

<img width="526" alt="スクリーンショット 2023-10-01 18 29 11" src="https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/1dfb7c28-d812-4799-810e-b285a8127cc9">

UI 実装済み ( Figma と異なるが 実装が正 )

tobe: 
- 送信するボタンでパスワード再登録のメールを送れるようにする。
- エラー時に文言出す。

_Originally posted by @ken-ty in https://github.com/Mayumi-Nakabayashi/withTone/issues/59#issuecomment-1742021088_

**Comment by sodateya** [comment]
## 実装しました
https://github.com/Mayumi-Nakabayashi/withTone/pull/118
